import streamlit as st

st.set_page_config(page_title="AI Plagiarism Detector", page_icon="🔍")

st.title("How It Works")

st.write("""
Welcome to the AI Plagiarism Detection App! Here's a step-by-step guide on how to use our platform to analyze and detect plagiarism in text.
""")

st.header("Step 1: Enter Text")
st.write("""
Start by entering the text you want to analyze into the provided text area. You can input any piece of written content, such as an essay, article, or document.
""")

st.header("Step 2: Click Analyze")
st.write("""
Once you've entered the text, click the 'Analyze' button. Our app will then process the input and provide you with insights into the text's authenticity.
""")

st.header("Step 3: View Analysis Results")
st.write("""
After clicking 'Analyze,' you'll see a detailed analysis of the text. This includes the perplexity score, burstiness score, and a visualization of the top repeated words.
""")

st.header("Step 4: Interpret Results")
st.write("""
Interpret the analysis results to understand the likelihood of the text being generated by AI. High perplexity and low burstiness may indicate AI-generated content.
""")

st.header("Step 5: Explore Further")
st.write("""
Feel free to explore additional features and details provided on our platform. For any questions or concerns, don't hesitate to reach out to us through the 'Contact Us' section.
""")
